platform :ios, '8.0'
xcodeproj 'INVBIMAssure/INVBIMAssure.xcodeproj'

link_with 'INVBIMAssure', 'INVBIMAssureTests'
pod 'Overcoat', '~>2.0'
pod 'VENTokenField', :git => 'git@github.com:rrossinvicara/VENTokenField.git'
pod 'FDKeychain', '~>1.0'
pod 'MBProgressHUD', '0.9'
pod 'FontAwesomeKit/FontAwesome', :git => 'git@github.com:rrossinvicara/FontAwesomeKit.git'
pod 'AWPagedArray', :git => 'git@github.com:rrossinvicara/AWPagedArray.git'
